language: node_js
node_js:
    - 0.10
script:
    - make test-cov
after_script:
    - make coveralls
    - make clean

notifications:
    email:
        recipients: tatsy.mail@gmail.com
        on_success: change
        on_failure: always
