language: node
node:
    1.0
before_script:
    - npm install
    - npm install -g mocha
script:
    - mocha

notifications:
    email:
        recipients: tatsy.mail@gmail.com
        on_success: change
        on_failure: always
